### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by benkoshy** [brandly/elm-rocket-league#3]
**Problem:**

I could not run / build.

**Reproduction Instructions:**

```shell

1. Clone the repository, and cd into directory.

2.  `npm install`

3. `npm run-script build`

The error reported is:

-- MISSING SOURCE DIRECTORY ------------------------------------------- elm.json

I need a valid elm.json file, but the "source-directories" field lists the
following directory:

    ../elm-physics/src


We seem to be missing a directory, and I'm not sure how to get it?

```

**Comment by brandly** [comment]
@BKSpurgeon hey! sorry, i didn't see this til now.

my car in this repo is mostly code lifted [from this PR](https://github.com/w0rm/elm-physics/pull/90). my repo depends on the `elm-physics` [package](https://package.elm-lang.org/packages/w0rm/elm-physics/), except the PR [includes a `Body.placeIn` function](https://github.com/w0rm/elm-physics/pull/90/files#diff-c571a85f2e6ebf8533e14ae7df2dbb08ec3c35022be70ba39a12722d2ebde537R521-R564), so i can't rely on the published package.

what i've done here is cloned that repo and checked out that PR, the `raycast-vehicle` branch. i have that code sitting next to my `elm-rocket-league` directory, and i tell Elm to go look for modules in that directory:

https://github.com/brandly/elm-rocket-league/blob/cd2d851cbc339f5dc1b5d8ced2318a1addc67639/elm.json#L3-L6

i think you could roughly get things running like this:

```
$ git clone git@github.com:brandly/elm-rocket-league.git
$ git clone git@github.com:w0rm/elm-physics.git
$ cd elm-physics
$ git checkout raycast-vehicle
$ cd ../elm-rocket-league
$ npm start
```

and then open `http://localhost:8000/src/Main.elm`

**Comment by BKSpurgeon** [comment]
Cheers,  I hope you try this out

**Comment by brandly** [comment]
this is deployed btw. i just realized the repo didn't have a link to it yet: https://brandly.github.io/elm-rocket-league/

i've got a plan to refactor things such that this weird `elm-physics` dependency will go away, and the repo will use the published package. in other words, if you wait long enough, the installation process will get a lot easier 😄

**Comment by benkoshy** [comment]
Got it working:

![image](https://user-images.githubusercontent.com/15097447/102178894-5690ac00-3efa-11eb-9e74-627f9296c743.png)
