### ISSUE TITLE
NaNs

### ISSUE THREAD

**Issue by brandly** [brandly/elm-rocket-league#8]
car `Body` gets corrupted with `NaN`s. they hit a bunch of fields at once on a single `Tick`, and the whole screen goes blank. haven't tracked down the source yet, but i'm probably dividing by 0 or something

**Comment by brandly** [comment]
i did some more digging:

`Quantity.ratio` returns a `NaN` when both arguments are `0`:

https://github.com/brandly/elm-rocket-league/blob/e844bfad0ffb93fb6cb7a8f25b7051a289a31f18/src/Main.elm#L1632-L1637

this pollutes `forwardImpulse`:

https://github.com/brandly/elm-rocket-league/blob/e844bfad0ffb93fb6cb7a8f25b7051a289a31f18/src/Main.elm#L1696-L1701

which pollutes `newCar`:

https://github.com/brandly/elm-rocket-league/blob/e844bfad0ffb93fb6cb7a8f25b7051a289a31f18/src/Main.elm#L1710-L1713

i still don't understand this car stuff deeply. @w0rm is the solution clear to you? i could catch the NaNs at the `skidInfo` level and return a default value instead, but that feels like duct tape.

**Comment by brandly** [comment]
_should_ `Quantity.ratio` be returning `1` when both arguments are `0`? it generally returns a 1 when the args are identical

**Comment by w0rm** [comment]
@brandly great troubleshooting! I’m glad this happens at the edge and not within elm-physics because that would be potentially hard to debug and fix. 

I will take a look how these values can be both 0. I think 0 / 0 = NaN is the general rule in JavaScript.

**Comment by w0rm** [comment]
I think I found a bug, `isSliding` should use `Quantity.greaterThan `. 

bullet3 https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp#L596
cannon.js https://github.com/schteppe/cannon.js/blob/master/src/objects/RaycastVehicle.js#L553


```
isSliding =
    Quantity.greaterThan (Quantity.times maximpSide maximpSide) impulseSquared

skidInfo =
    if isSliding then
        Quantity.ratio maximpSide (Quantity.sqrt impulseSquared)

    else
        1
```

**Comment by brandly** [comment]
@w0rm looks like it works! drifting generally feels a lot better, and the car has more control now. thanks for the help!!!

**Comment by w0rm** [comment]
@brandly awesome! I'm so glad we were able to fix this!
